set (CONDUCTEO_VERSION_MAJOR "5" CACHE STRING "major version"  FORCE)
set (CONDUCTEO_VERSION_MINOR "0" CACHE STRING "minor version"  FORCE)
set (CONDUCTEO_VERSION_PATCH "0" CACHE STRING "patch revision" FORCE)
